ALTER TABLE event_ticket_bookings
  ADD COLUMN IF NOT EXISTS paymentMethod VARCHAR(50),
  ADD COLUMN IF NOT EXISTS paymentDate TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS discountAmount FLOAT,
  ADD COLUMN IF NOT EXISTS discountCode VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cancellationReason TEXT; 